[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remmpings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable",
]

fs_permissions = [
    { access = "read-write", path = "/home/fanshuai/foundry-launchpad/script/deployment/target/input.json" },
    { access = "read-write", path = "/home/fanshuai/foundry-launchpad/script/deployment/target/output.json" },
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },

]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
